
#Service Name
spring:
  application:
    name: API-GETEWAY
    
#Routing Configuration

  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/dept/**
          
          
    
    

#Eureka configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
         defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost