
#Service Name
spring:
  application:
    name: API-GETEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**   
        filters:
        - name: CircuitBreaker
          args:
            name: USER_SERVICE
            fallbackuri: forward:/userServiceFallBack 
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/dept/**       
        filters:
        - name: CircuitBreaker
          args:
            name: DEPARTMENT-SERVICE
            fallbackuri: forward:/departmentServiceFallBack  
          


#Eureka configuration
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#         defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost